name: Node.js CI

on: [pull_request]

jobs:
  build:
    name: Build and Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install npm dependencies
        run: npm install

      - name: Set up MySQL
        uses: mysql/setup-mysql@v1
        with:
          mysql-version: '8.0'
          server-port: '3306'
          root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          config-overrides: |
            max_connections: 500
      
      - name: Run Integration Tests
        run: npm test:integration
