name: Packer Validator

on: [pull_request]

jobs:
  packer:
    name: Packer Validator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Web App
        run: zip -r webapp.zip ./

      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Initiate Packer template
        run: packer fmt -check -recursive ./packerconfig/main.pkr.hcl
      
      - name: Validating Packer Formatting
        run: |
          packer fmt -check -recursive ./packer
          if [ $? -ne 0 ]; then
            echo "Packer template formatting issues found. Please run 'packer fmt' to fix them."
            exit 1
          fi

      - name: Initiate Packer template
        run: packer init ./packerconfig/main.pkr.hcl

      - name: Validate Packer template
        run: packer validate ./packerconfig/main.pkr.hcl
      

