name: Packer Validator

on: [pull_request]

jobs:
  packer:
    name: Packer Validator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Initiate Packer template
        run: packer init ./packer/main.pkr.hcl

      - name: Validate Packer template
        run: packer validate ./packer/main.pkr.hcl

